name: Call a reusable workflow and use its outputs

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  call-workflow-passing-data:
    uses: demo-canarys/template-repo/.github/workflows/main.yml@main
    with:
      username: Siri
